version: '3.9'

volumes:
  app:
  postgres_data:
  redis-conf:

services:
  api:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: api
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - app:/usr/src/app/
    env_file:
      - .env
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  
  redis:
    image: redis:latest
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      - redis-conf:/usr/local/etc/redis/redis.conf

  test:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: api_test
    depends_on:
      - db
    volumes:
      - app:/usr/src/app/
    env_file:
      - .env
    command: sh -c "python manage.py test tests"
